# Usamos una imagen ligera de Python (Best Practice)
FROM python:3.9-slim

WORKDIR /app

# Instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código
COPY . .

# Exponemos el puerto
EXPOSE 5000

# Comando de inicio
CMD ["python", "app.py"]